name: Deno CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x # Use a specific version or v2.x for latest 2.x

      - name: Run Deno Lint
        run: deno lint

      - name: Run Deno Format Check
        run: deno fmt --check

  test:
    runs-on: ubuntu-latest
    needs: lint-and-format # Optionally make tests depend on linting/formatting passing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Install system dependencies (ffmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Generate version file
        run: deno run --allow-read --allow-write scripts/generate_version.ts

      - name: Run Deno Tests
        run: deno test --import-map=import_map.json --no-check --allow-net --allow-read --allow-run --allow-write --allow-env
        # Note: --allow-net might be needed if any test makes network requests.
        # The current tests for amusic.ts do not seem to require network access.
        # --allow-env is needed for Deno.makeTempDir and other environment interactions.
        # --allow-write is needed for ffmpeg/fpcalc creating temp files and for tests creating test_run_files
        # --allow-read is needed for reading script files and audio samples
        # --allow-run is needed for Deno.Command to run ffmpeg, ffprobe, fpcalc
